[package]
name = "beat_saber_map_importer_rs"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
eframe = "0.31.1"
image = "0.25.5"
open = "5.3.2"
regex = "1.11.1"
winreg = "0.55.0"
zip = "2.2.3"
